### ISSUE TITLE
AttributeError: 'PosixPath' object has no attribute 'with_stem'

### ISSUE THREAD

**Issue by ngys321** [omriav/blended-diffusion#13]
Thanks for opening your code. I really appreciated that.

I tried to run your code in the Google Colab with GPU Runtime.

I got an error. And I couldn't find any solution despite of googling...

The error message is as follows : 
`AttributeError: 'PosixPath' object has no attribute 'with_stem'`

I think kinda related to "pathlib" module. maybe it's due to the fact that pathlib doesn't work well with latest python 3.x version which I'm using.

I hope this error will be solved soon QQ

**-----detail description-------**

**I run the terminal argument like this as follows :** 
`python main.py -p "rock" -i "input_example/img.png" --mask "input_example/mask.png" --output_path "output" --batch_size 1`

**And, I got this whole bunch of error messages as follow :** 
`Using device: cuda:0
tcmalloc: large alloc 2209964032 bytes == 0x89ebe000 @  0x7fbdefa2cb6b 0x7fbdefa4c379 0x7fbd30b1026e 0x7fbd30b119e2 0x7fbd334aeee1 0x7fbdd598e236 0x7fbdd541ef98 0x593784 0x594731 0x548cc1 0x51566f 0x549e0e 0x593fce 0x5118f8 0x549e0e 0x4bcb19 0x59582d 0x595b69 0x62026d 0x55de15 0x59af67 0x515655 0x549e0e 0x4bca8a 0x5134a6 0x549576 0x593fce 0x548ae9 0x5127f1 0x4bc98a 0x532b86
Setting up [LPIPS] perceptual loss: trunk [vgg], v[0.1], spatial [off]
Loading model from: /usr/local/lib/python3.7/dist-packages/lpips/weights/v0.1/vgg.pth
Start iterations 0
  0% 0/75 [00:00<?, ?it/s]clip_loss - 867.99
range_loss - 0.00
Traceback (most recent call last):
  File "main.py", line 8, in <module>
    image_editor.edit_image_by_prompt()
  File "/content/drive/MyDrive/ws/blended-diffusion/optimization/image_editor.py", line 266, in edit_image_by_prompt
    visualization_path = visualization_path.with_stem(
AttributeError: 'PosixPath' object has no attribute 'with_stem'
  0% 0/75 [00:01<?, ?it/s]`

**Comment by ngys321** [comment]
I solved it!! It was a python version problem!

I think the code works well when "python version >= 3.9" setting!
